; PlatformIO Project Configuration File
;
; Workshop 6.2 — чотири задачі FreeRTOS з різними пріоритетами (ESP-IDF, ESP32-C3)

[platformio]
default_envs = esp32-c3-devkitm-1

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = espidf
monitor_speed = 115200
