#pragma once
#include <cstdint>

struct Config {
    // PWM generated by GP timer ISR bit-banging GPIO – LEDC is intentionally not used.
    static constexpr uint32_t PWM_FREQ_HZ         = 10'000;     // 10 kHz carrier
    // 1 MHz tick gives 100 ticks per 10 kHz period (100 µs),
    // which divides evenly into 25 % steps (25 / 50 / 75 ticks). Lower resolution
    // would round unevenly; higher is unnecessary for this frequency.
    static constexpr uint32_t TIMER_RESOLUTION_HZ = 1'000'000;  // 1 µs / tick

    // Button timing 
    static constexpr uint32_t MIN_PRESS_US  =     50'000;  // debounce: ignore < 50 ms
    static constexpr uint32_t LONG_PRESS_US =    1000'000;  // >= 500 ms → long press

    // Mode timing
    static constexpr uint64_t AUTO_ADVANCE_US  = 2'000'000;  // auto step interval: 5 s
    static constexpr uint64_t IDLE_TIMEOUT_US  = 10'000'000; // manual idle → auto: 10 s

    // Controller task
    static constexpr uint32_t CTRL_TASK_STACK    = 4096;
    static constexpr uint32_t CTRL_TASK_PRIORITY = 5;

    // LED brightness steps shared by all LED implementations
    static constexpr uint8_t DUTY_STEPS[] = {0, 25, 50, 75, 100};
    static constexpr size_t  NUM_STEPS    = sizeof(DUTY_STEPS) / sizeof(DUTY_STEPS[0]);
};
